Document: ruby-ntlm-solnet
Title: Debian ruby-ntlm-solnet Manual
Author: <insert document author here>
Abstract: This manual describes what ruby-ntlm-solnet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ruby-ntlm-solnet/ruby-ntlm-solnet.sgml.gz

Format: postscript
Files: /usr/share/doc/ruby-ntlm-solnet/ruby-ntlm-solnet.ps.gz

Format: text
Files: /usr/share/doc/ruby-ntlm-solnet/ruby-ntlm-solnet.text.gz

Format: HTML
Index: /usr/share/doc/ruby-ntlm-solnet/html/index.html
Files: /usr/share/doc/ruby-ntlm-solnet/html/*.html
