---
name: build

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019]
        ruby: ['3.0', '3.1', '3.2', '3.3', 'head', 'truffleruby-head']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
